### ISSUE TITLE
6.0.1 BLUE_WHITE radio mod seems to be corrupted.

### ISSUE THREAD

**Issue by YannickF** [hvdwolf/Joying-RootAssistant#2]
Hello

I've juste tried to install the 6.0.1 BLUE_WHITE mod on my JOYING 6.0.1 android radio but at the end of the adb installation, the app (apk file) is not installed. The file manager indicates that the file had a problem during verification. 
So the radio app is not available ! 
And the I reinstalled the default app without problems.

Could you check the file ?
Regards

**Comment by hvdwolf** [comment]
The file is OK. I installed it myself as well.
There are weird issues going on with this 6.0.1. It almost seems as if the dalvik cache is not always cleaned upon installing, actually pushing, a new application. I have experienced it myself, and gustden who is working on the SofiaServer mods, as well.

**Comment by YannickF** [comment]
OK… do if the file is OK, what is the method to install it without problem ?  

Regards

**Comment by Clandaries** [comment]
Installed it to my Joying device and it is running.

**Comment by YannickF** [comment]
Hello

I have just reinstalled the last version of Android 6.0.1 for Joying head Unit.
Then, I install adb, superSU without any problem. adb is authrized for SuperSU.

But when I install your mod for the radio app, nothing change….. I really don’t understand why.

The apk file is copied to /sdcard (but not installable from there), all other command via adb are OK, the original apk fil is renamed with .old, the new one is copied…. but the app is still exactly the same.

It’s really weird !

**Comment by hvdwolf** [comment]
It is indeed really weird. When I was just on 6.0.1 there were several users that installed the radio app without problems, whereas I could not install it myself.
Then I updated to the 25th May version and I could install it without problems.  And now you seem to have problems.
I really have no idea other than that the Dalvik cache is not updated, as is the suspicion of both me and gustden.

**Comment by Clandaries** [comment]
I had to install it and go back to original app about 25 times untill it worked for me...

But now everything is running.

**Comment by hvdwolf** [comment]
It is really terrible. I slightly modified the existing one (old frequency ruler back; center text on buttons, leftover from previous butons) and installed it. It worked fine. After about half an hour I remembered that it is better to reboot, so I rebooted.
The radio app does no longer work and is no longer installed.
By now I'm getting crazy.

**Comment by YannickF** [comment]
Android seems to be a a strange world !

If you want a beta tester, I can test your future apps.

**Comment by hvdwolf** [comment]
Hi, I did rebuild the 6.0.1 again.
Please try from my Releases page: the 20170625.
https://github.com/hvdwolf/Joying-RootAssistant/releases/

What I did my self:
- reboot
- exit autostarting Radio app
- install radio
- reboot
- check if it is working

Actually I did this a few number of times switching between my mod and the default joying version. It worked every time: 3x mine and 2x default.

**Comment by YannickF** [comment]
Hi



The problem still exists with your new version.
The new app is not installed, the head unit still launch the original Joying radio app.
There is no error message during install.sh script, the new .apk file is in /sdcard, but is not launchable (error during analysis the package)

I don't understand anything !!!!

How do you « exit autostarting Radio App » ???? this is the only thing I didn’t do…. I just kill the app, the reboot, so App is not launched at reboot)

**Comment by Clandaries** [comment]
I think you have to do a real reboot.

I think the Joying reboot is not a 100% reboot.

If i use reboot apps like QuickBoot, it lasts longer to reboot and my subwoofer is making some noise.

After those reboots the message with says optimizing app is comming.

Maybe this helps us?

**Comment by YannickF** [comment]
You’re right, Joying reboot is not a real reboot.
If I send adb shell ‘su reboot’, the reboot lasts longer, there is a noise in loud speaker.

So, I rebooted, installed you Radio App, , rebooted, and the original App is still present…. no mods !

**Comment by YannickF** [comment]
Hello

With adb shell I removed the /system/app/JY-1-C9-Radio folder….

the radio is still working !!!!!! (after 2 reboot)

**Comment by YannickF** [comment]
I finally installed your mod app ! Not really understood why it works now !

with adb shell I removed the folder /system/app/JY-1-C9-Radio-V1.0
I also removed the shortcut icon to Radio app
Then I made a new JY-1-C9-Radio-V1.0 folder with correct rights (755)
I rebooted

At this moment it was impossible to make the radio working.

Then I use your script to install the original Joying app.
the icon re-appears…. I then launched the radio app : it works 

With the radio ON, I installed the mod app (using your script), 
the script will switch the radio off
I didn't reboot, the shortcut icon is still here (if I reboot, the icon disappears)… but is not functionnal. I clicked it 3 times.
The third times, I had an error : « Radio app doesn’t respond : wait / OK »
I click the Home button, and the radio is now working… with you mods !!!

**Comment by hvdwolf** [comment]
Thanks all for testing.
I'm afraid I still don't understand why it sometimes works and why not on other occasions.
Given the fact that you removed everything also means that the dalvik autocache should clean itself.
Based on your testing I will do some further tests myself (remove apk, remove cache, install mod)

W.r.t. the radio app not being there and still hear it play: I already mentioned that a couple of times in the several threads on XDA and carjoying. Joying (or SYU) uses a 2-step approach. The CarRadio apk and the Radio apk. The CarRadio is the real app "talking" to the hardware. The Radio app is just the visual aspect of it.

**Comment by YannickF** [comment]
HEllo


Your new App is great. Radio Mods are installed without any problems now.
But, I install the SofiaServer mod in order to have Google Voice with the SRC button.

Just after installation finished, the User Interface (Home button) was not working.
I can choose UI01 and UI02 : they works.
But UI03 not.

Any ideas ?

**Comment by hvdwolf** [comment]
Actually this is something else than how this thread started. To keep bugs separated this question/answer should stop or deal with the original topic. 
I will try to answer and close this specific thread. If necessary we can restart in anotherbut I don't think it is necessary.
You mention you want to use Google Voice. The Google app is incompatible with UI03.
Or you switch to UI02 or UI01, or you need to remove the Google App. It's a known bug and unfortunately still not solved by Joying.
