### ISSUE TITLE
app not installed

### ISSUE THREAD

**Issue by LoGnarlo** [hvdwolf/Joying-RootAssistant#3]
hello 
I use your mods for months without any problems, but since the latest versions I can not install them anymore. I have an uls01n2 with the latest firmware and root privileges, but every time I try to replace the  apk, when I reboot the HU,  start the radio automatically, but if I try to open the app, android reports that " App is not installed ".
I've tried both versions (5.1.1 and 6.0.1) through install.bat (it completes the procedure correctly), either to manually replace the apk, but without results.

you can give me some suggestions? something I'm wrong?
regards

**Comment by hvdwolf** [comment]
I hear more issues from users. 
Did you download the apks directly or via the Releases page?

**Comment by LoGnarlo** [comment]
I tried in both ways

**Comment by hvdwolf** [comment]
I'm still looking into this. This behaviour never happened on 5.1.1 and does happen on 6.0.1
I had it myself as well where others could install the same mods.
Then suddenly I could install my own mods again ,but now other users complain. I still have no idea what causes this.
It works for one and not for the other on 6.0.1

**Comment by LoGnarlo** [comment]
It's really a weird thing. I am waiting for your updates!
If you need a beta tester, I'm available :)

**Comment by hvdwolf** [comment]
Hi, I did rebuild the 6.0.1 again.
Please try from my Releases page: the 20170625.
https://github.com/hvdwolf/Joying-RootAssistant/releases/

What I did my self:
- reboot
- exit autostarting Radio app
- install radio
- reboot
- check if it is working

Actually I did this a few number of times switching between my mod and the default joying version. It worked every time: 3x mine and 2x default.

**Comment by LoGnarlo** [comment]
I tried it twice but it still does not work.
"App not installed"

:(

**Comment by hvdwolf** [comment]
I now uploaded the original zip to my google drive. Please try one more time.

https://drive.google.com/open?id=0B4J3kKZoV78-WjJfT0JjQ1NFNWM

I'm currently out of options: I tried on linux with/without framework-res.apk as "resources" apk,
and I did exactly the same on Windows 10.
All versions don't seem to work right.

**Comment by LoGnarlo** [comment]
Same result. I also tried downloading the zip directly from the hu, but I still have the same error.

**Comment by YannickF** [comment]
Same problem for me.

Modified App is not installed ..... the original one is still present. I tried all versions, the only one which install correctly is the original Joying one. all others can't be installed because " A problem occurs during package analysis" (this message appears when using the file manager.

**Comment by LoGnarlo** [comment]
You do not have to install the app normally, but simply replace it with the original one

**Comment by YannickF** [comment]
Of course I'm using the install.sh script..... without any errors. With the script, .apk file is copied on /sdcard and should replace the original one.
 if you click it you have the error message.... Not really a good thing I think !

**Comment by LoGnarlo** [comment]
yeah! Finally it works! Thanks to version 1.0.1 of your app! This morning I tried with 1.0 and it was not working yet, but now it goes great!
The perfection now, would be, having the various colored versions for 6.0.1 :)
