### ISSUE TITLE
Missing SuperSU

### ISSUE THREAD

**Issue by ccrisan** [hvdwolf/Joying-RootAssistant#5]
I can't seem to find any rooting script or SuperSU archive in your [latest 2.6 release](https://github.com/hvdwolf/Joying-RootAssistant/releases/tag/2.6). Am I missing something obvious?

**Comment by hvdwolf** [comment]
Sorry. I missed this one completely.

No, there is no rooting script inside the apk.
The rooting is done via a separate script which you can find [here](https://hvdwolf.github.io/Joying-RootAssistant/rooting.html).

**Comment by ccrisan** [comment]
Thanks.
