### ISSUE TITLE
Forcing device into Portrait mode

### ISSUE THREAD

**Issue by tneil** [hvdwolf/Joying-RootAssistant#7]
Hi There,

I've been trying to force the Joying device ([10" unit](https://www.joyingauto.com/au-warehouse-android-8-0-car-sound-system-big-touch-screen-4gb-stereo-upgrade.html)) into Portrait mode.

I have tried the following ADB command:
adb shell content insert --uri content://settings/system --bind name:s:user_rotation --bind value:i:0

And I have also tried updating the build.prop file using these steps:
https://tinkerboarding.co.uk/forum/thread-574.html

When updating the build.prop file I noticed that the ro.sf.hwrotation property wasn't in the file when I pulled it.  I tried adding it to the file and updating it (confirmed it was updated with a follow-up pull of the file).

I also tried the following:
adb shell settings put system accelerometer_rotation 0
adb shell settings put system user_rotation 0

None of the approaches will force the device into portrait mode.  Rebooted the device after each attempt

Any suggestions?

I'm told that it could be possible using the following code by an app with root permissions:

`import android.provider.Settings;
// You can get ContentResolver from the Context
Settings.System.putInt(getContentResolver(), Settings.System.ACCELEROMETER_ROTATION, 0);
Settings.System.putInt(getContentResolver(), Settings.System.USER_ROTATION, 0);`

**Comment by hvdwolf** [comment]
Please do not use this issues list for these kind of questions. Please ask these questions on XDA in the general thread: https://forum.xda-developers.com/android-auto/android-head-units

or the Joying Extra Tools thread: https://forum.xda-developers.com/android-auto/android-head-units/joying-extra-tools-apk-apk-to-help-t3628200

anyway: 
Use "adb shell setprop ro.sf.hwrotation 90"
It is not necessary to add this to the build.prop as it will stay active until you flash a new firmware.
If you want to edit the build.prop you first need to make the /system read-write.
all of these things can be found in XDA.

**Comment by tneil** [comment]
Apologies for the wrong place to post.  This is something you may want to consider adding to the Extra tools APK as more and more people are looking to run the 10.1" joying unit in a portrait orientation.

Thanks for the answer :)

**Comment by tneil** [comment]
Just as an update.. apparently the ro.sf.hwrotation is no longer supported on newer versions of Android.  Thought I would just let you know as an FYI :)

**Comment by hvdwolf** [comment]
Thanks. I didn't know that, but just googled that. It seems you can now only do it programmatically from an app.
