### ISSUE TITLE
Unable to authorize adb client

### ISSUE THREAD

**Issue by walnut-engineering** [hvdwolf/Joying-RootAssistant#8]
Hello, I am trying to use your app on a joying sp9853i and am getting stuck when trying to root.  I am able to enable adb over wifi via your app but when I try to connect I never get the authorization request on the Joying headunit.  I very briefly see an icon appear on the taskbar when I initiate the connection so I assume this is the dialog box.  No clue why it never appears.  Do you know a work around for this?

**Comment by hvdwolf** [comment]
I should remove that on a sp9853i. FYT/Joying "closed" the adb, You can't use it.

And for rooting itself see [howto root joying sc9853i head unit](https://forum.xda-developers.com/android-auto/android-head-units/howto-root-joying-sc9853i-head-unit-t3915530) on the XDA forum

**Comment by walnut-engineering** [comment]
Ah, that explains it - thanks for the info!
